### ISSUE TITLE
Question: Is this also usable for packages I don't make myself?

### ISSUE THREAD

**Issue by frankhommers** [baseclass/Contrib.Nuget#16]
I was wondering if this is also usable for packages that I won't make myself? For example I have implemented my solution to work with IDbConnection and I want to supply my solution with different DLL's from packages like Npgsql, ODP.NET etc. 

Or am I misunderstanding the purpose of this?

**Comment by mnivet** [comment]
I suppose you're question is about Baseclass.Contrib.Nuget.Output

If you want to create a nuget package from your solution that depends on other packages (Npgsql and others), you can write a nuspec file that will declare a dependency on Baseclass.Contrib.Nuget.Output and that copy DLLS from some nuget packages that you depends on into the output folder of your package.

This can works, but pay attention that you will break dependency management of NuGet by doing this, because you're package won't have a dependency on other packages like Npgsql , but will have copy of one version of the dlls of those packages.

Even if this package can hide dependencies, I think it's better to use it for native libraries (that aren't natively handled by NuGet), or custom files that you need to be in the output folder (a licence file or something like that)

**Comment by romerod** [comment]
The usual purpose is to use it as dependency for your own package, it depends on the licensing of the other dlls if you should reship the dependencies in your own packages.

A side from native libraries it can also be used to copy .net assemblies which you don't need a reference to because they are loaded dynamically.
