### ISSUE TITLE
Cannot install in MonoAndroid or WindowsPhone project

### ISSUE THREAD

**Issue by luzianscherrer** [baseclass/Contrib.Nuget#24]
I'm trying to get Baseclass.Contrib.Nuget.Output installed in a Xamarin Android and Windows Phone project in Visual Studio 2015 due to a dependency. Unfortunately that does not work:

    PM> Get-Project -all | Install-Package Baseclass.Contrib.Nuget.Output
    Attempting to gather dependencies information for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with respect to project 'SocketTestSap.Droid', targeting 'MonoAndroid,Version=v5.0'
    Attempting to resolve dependencies for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with DependencyBehavior 'Lowest'
    Resolving actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
    Resolved actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
    Install failed. Rolling back...
    Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in project 'SocketTestSap.Droid'
    Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in folder 'C:\Users\me\documents\visual studio 2015\Projects\SocketTestSap\packages'
    Install-Package : Could not install package 'Baseclass.Contrib.Nuget.Output 2.1.0'. You are trying to install this package 
    into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content 
    files that are compatible with that framework. For more information, contact the package author.
    ....
    Attempting to gather dependencies information for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with respect to project 'SocketTestSap.WinPhone', targeting 'WindowsPhone,Version=v8.0'
    Attempting to resolve dependencies for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with DependencyBehavior 'Lowest'
    Resolving actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
    Resolved actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
    Install failed. Rolling back...
    Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in project 'SocketTestSap.WinPhone'
    Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in folder 'C:\Users\me\documents\visual studio 2015\Projects\SocketTestSap\packages'
    Install-Package : Could not install package 'Baseclass.Contrib.Nuget.Output 2.1.0'. You are trying to install this package 
    into a project that targets 'WindowsPhone,Version=v8.0', but the package does not contain any assembly references or content 
    files that are compatible with that framework. For more information, contact the package author.
    ....

Is there probably a workaround for this?

**Comment by romerod** [comment]
This package only makes sense as dependency to another package.

Is the output you have sent just to show me the problem?

The package currently only supports net40, you could try to change the nuspec and build the package yourself and send me a PR if it's working


-------- Ursprüngliche Nachricht --------
Von: Luzian Scherrer <notifications@github.com>
Datum: 20.08.2015 09:33 (GMT+01:00)
An: "baseclass/Contrib.Nuget" <Contrib.Nuget@noreply.github.com>
Betreff: [Contrib.Nuget] Cannot install in MonoAndroid or WindowsPhone project (#24)


I'm trying to get Baseclass.Contrib.Nuget.Output installed in a Xamarin Android and Windows Phone project in Visual Studio 2015 due to a dependency. Unfortunately that does not work:

PM> Get-Project -all | Install-Package Baseclass.Contrib.Nuget.Output
Attempting to gather dependencies information for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with respect to project 'SocketTestSap.Droid', targeting 'MonoAndroid,Version=v5.0'
Attempting to resolve dependencies for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
Resolved actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
Install failed. Rolling back...
Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in project 'SocketTestSap.Droid'
Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in folder 'C:\Users\me\documents\visual studio 2015\Projects\SocketTestSap\packages'
Install-Package : Could not install package 'Baseclass.Contrib.Nuget.Output 2.1.0'. You are trying to install this package
into a project that targets 'MonoAndroid,Version=v5.0', but the package does not contain any assembly references or content
files that are compatible with that framework. For more information, contact the package author.
....
Attempting to gather dependencies information for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with respect to project 'SocketTestSap.WinPhone', targeting 'WindowsPhone,Version=v8.0'
Attempting to resolve dependencies for package 'Baseclass.Contrib.Nuget.Output.2.1.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
Resolved actions to install package 'Baseclass.Contrib.Nuget.Output.2.1.0'
Install failed. Rolling back...
Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in project 'SocketTestSap.WinPhone'
Package 'Baseclass.Contrib.Nuget.Output 2.1.0' does not exist in folder 'C:\Users\me\documents\visual studio 2015\Projects\SocketTestSap\packages'
Install-Package : Could not install package 'Baseclass.Contrib.Nuget.Output 2.1.0'. You are trying to install this package
into a project that targets 'WindowsPhone,Version=v8.0', but the package does not contain any assembly references or content
files that are compatible with that framework. For more information, contact the package author.
....


Is there probably a workaround for this?

-

**Comment by luzianscherrer** [comment]
Yes, exactly. I'm trying to install [libsodium-net](https://github.com/adamcaudill/libsodium-net) which requires Baseclass.Controb.Nuget.Output. I just wanted to show the error. The author of libsodium-net recommended to ask you about it [in this thread](https://github.com/adamcaudill/libsodium-net/issues/115).

I will try to change the nuspec, but I'm really a newbie in the whole C#/NuGet world :) You'll get a PR if I can get something going.

**Comment by adamcaudill** [comment]
Maintainer of libsodium-net here, I think this issue is purely on the side of my project - or so it seems. I think this can be closed.
